CREATE TABLE PRODUCTO(
    cod_pro int not null AUTO_INCREMENT,
    nom_pro varchar(50) null,
    des_pro varchar(150) null,
    pre_pro numeric(6,2) null,
    estado int null, 
    rutima_pro varchar(100) null,
    stock int not null,
    CONSTRAINT pk_producto
    PRIMARY KEY (cod_pro)
);
ALTER TABLE PRODUCTO ADD rutima_pro varchar(100) null;
INSERT INTO PRODUCTO (nom_pro, des_pro, pre_pro, estado, rutima_pro, stock)
VALUES ('Zapatillas Nike', 'Producto de la mas alta calidad y exclusividad.', 35000, 1, 'zapatillas.png', 20),
('Poleron negro', 'Hoddie con costuras firmes y estilo esbelto.', 15000, 1, 'poleron2.png', 43);

CREATE TABLE USUARIO(
    cod_usu int not null AUTO_INCREMENT,
    nom_usu varchar(50),
    ape_usu varchar(50),
    ema_usu varchar(50) not null,
    pass_usu varchar(20) not null,
    estado int not null,
    CONSTRAINT pk_usuario
    PRIMARY KEY (cod_usu)
);
INSERT INTO USUARIO (nom_usu, ape_usu, ema_usu, pass_usu, estado)
VALUES ('Usuario','Demo', 'correo@example.com', '123456', 1);

CREATE TABLE PEDIDO
(
    cod_ped int AUTO_INCREMENT not null,
    cod_usu int not null,
    cod_pro int not null,
    fec_ped datetime not null,
    estado int not null,
    dir_usu varchar(50) not null,
    tel_usu varchar(12) not null,
    PRIMARY KEY (cod_ped)

);
CREATE TABLE venta
(
    cod_ven int AUTO_INCREMENT not null,
    cod_usu int not null,
    tot_ven int not null,
    fec_ven datetime not null,
    PRIMARY KEY (cod_ven)
);
CREATE TABLE venta_producto
(
    cod_ven_pro int AUTO_INCREMENT not null,
    cod_ven int not null,
    cod_pro int not null,
    can_ven_pro int not null,
    pre_ven_pro datetime not null,
    stotal_ven_pro int not null,
    PRIMARY KEY (cod_ven_pro)
);
--Envios
CREATE TABLE envio
(
    cod_envio int AUTO_INCREMENT not null,
    pais_envio varchar(100) not null,
    dir_envio varchar(200) not null,
    dir_envio2 varchar(200) not null,
    cod_ven int not null,
    CONSTRAINT pk_envio
    PRIMARY KEY (cod_envio)
);

CREATE TABLE region
(
    cod_region int AUTO_INCREMENT not null,
    nom_region varchar(200) not null,
    CONSTRAINT pk_region
    PRIMARY KEY (cod_region)
);

CREATE TABLE comuna
(
    cod_comuna int AUTO_INCREMENT not null,
    nom_comuna varchar(200) not null,
    CONSTRAINT pk_comuna
    PRIMARY KEY (cod_comuna)
);
ALTER TABLE USUARIO ADD phone_usu varchar(12) null;
ALTER TABLE comuna ADD cod_region int not null;
ALTER TABLE envio ADD cod_comuna int not null;
ALTER TABLE envio ADD comentario varchar(500) null;

--poblar tabla region - comuna

INSERT INTO region VALUES(1,'Arica y Parinacota');
INSERT INTO region VALUES(2,'Tarapacá');
INSERT INTO region VALUES(3,'Antofagasta');
INSERT INTO region VALUES(4,'Atacama');
INSERT INTO region VALUES(5,'Coquimbo');
INSERT INTO region VALUES(6,'Valparaíso');
INSERT INTO region VALUES(7,'Metropolitana de Santiago');
INSERT INTO region VALUES(8,'Libertador General Bernardo O’Higgins');
INSERT INTO region VALUES(9,'Maule');
INSERT INTO region VALUES(10,'Ñuble');
INSERT INTO region VALUES(11,'Biobío');
INSERT INTO region VALUES(12,'La Araucanía');
INSERT INTO region VALUES(13,'Los Ríos');
INSERT INTO region VALUES(14,'Los Lagos');
INSERT INTO region VALUES(15,'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO region VALUES(16,'Magallanes y Antártica Chilena');


INSERT INTO COMUNA VALUES (1,'Arica',1);
INSERT INTO COMUNA VALUES (2,'Camarones',1);
INSERT INTO COMUNA VALUES (3,'General Lagos',1);
INSERT INTO COMUNA VALUES (4,'Putre',1);
INSERT INTO COMUNA VALUES (5,'Alto Hospicio',2);
INSERT INTO COMUNA VALUES (6,'Iquique',2);
INSERT INTO COMUNA VALUES (7,'Camiña',2);
INSERT INTO COMUNA VALUES (8,'Colchane',2);
INSERT INTO COMUNA VALUES (9,'Huara',2);
INSERT INTO COMUNA VALUES (10,'Pica',2);
INSERT INTO COMUNA VALUES (11,'Pozo Almonte',2);
INSERT INTO COMUNA VALUES (12,'Antofagasta',3);
INSERT INTO COMUNA VALUES (13,'Mejillones',3);
INSERT INTO COMUNA VALUES (14,'Sierra Gorda',3);
INSERT INTO COMUNA VALUES (15,'Taltal',3);
INSERT INTO COMUNA VALUES (16,'Calama',3);
INSERT INTO COMUNA VALUES (17,'Ollague',3);
INSERT INTO COMUNA VALUES (18,'San Pedro de Atacama',3);
INSERT INTO COMUNA VALUES (19,'María Elena',3);
INSERT INTO COMUNA VALUES (20,'Tocopilla',3);
INSERT INTO COMUNA VALUES (21,'Chañaral',4);
INSERT INTO COMUNA VALUES (22,'Diego de Almagro',4);
INSERT INTO COMUNA VALUES (23,'Caldera',4);
INSERT INTO COMUNA VALUES (24,'Copiapó',4);
INSERT INTO COMUNA VALUES (25,'Tierra Amarilla',4);
INSERT INTO COMUNA VALUES (26,'Alto del Carmen',4);
INSERT INTO COMUNA VALUES (27,'Freirina',4);
INSERT INTO COMUNA VALUES (28,'Huasco',4);
INSERT INTO COMUNA VALUES (29,'Vallenar',4);
INSERT INTO COMUNA VALUES (30,'Canela',5);
INSERT INTO COMUNA VALUES (31,'Illapel',5);
INSERT INTO COMUNA VALUES (32,'Los Vilos',5);
INSERT INTO COMUNA VALUES (33,'Salamanca',5);
INSERT INTO COMUNA VALUES (34,'Andacollo',5);
INSERT INTO COMUNA VALUES (35,'Coquimbo',5);
INSERT INTO COMUNA VALUES (36,'La Higuera',5);
INSERT INTO COMUNA VALUES (37,'La Serena',5);
INSERT INTO COMUNA VALUES (38,'Paihuaco',5);
INSERT INTO COMUNA VALUES (39,'Vicuña',5);
INSERT INTO COMUNA VALUES (40,'Combarbalá',5);
INSERT INTO COMUNA VALUES (41,'Monte Patria',5);
INSERT INTO COMUNA VALUES (42,'Ovalle',5);
INSERT INTO COMUNA VALUES (43,'Punitaqui',5);
INSERT INTO COMUNA VALUES (44,'Río Hurtado',5);
INSERT INTO COMUNA VALUES (45,'Isla de Pascua',6);
INSERT INTO COMUNA VALUES (46,'Calle Larga',6);
INSERT INTO COMUNA VALUES (47,'Los Andes',6);
INSERT INTO COMUNA VALUES (48,'Rinconada',6);
INSERT INTO COMUNA VALUES (49,'San Esteban',6);
INSERT INTO COMUNA VALUES (50,'La Ligua',6);
INSERT INTO COMUNA VALUES (51,'Papudo',6);
INSERT INTO COMUNA VALUES (52,'Petorca',6);
INSERT INTO COMUNA VALUES (53,'Zapallar',6);
INSERT INTO COMUNA VALUES (54,'Hijuelas',6);
INSERT INTO COMUNA VALUES (55,'La Calera',6);
INSERT INTO COMUNA VALUES (56,'La Cruz',6);
INSERT INTO COMUNA VALUES (57,'Limache',6);
INSERT INTO COMUNA VALUES (58,'Nogales',6);
INSERT INTO COMUNA VALUES (59,'Olmué',6);
INSERT INTO COMUNA VALUES (60,'Quillota',6);
INSERT INTO COMUNA VALUES (61,'Algarrobo',6);
INSERT INTO COMUNA VALUES (62,'Cartagena',6);
INSERT INTO COMUNA VALUES (63,'El Quisco',6);
INSERT INTO COMUNA VALUES (64,'El Tabo',6);
INSERT INTO COMUNA VALUES (65,'San Antonio',6);
INSERT INTO COMUNA VALUES (66,'Santo Domingo',6);
INSERT INTO COMUNA VALUES (67,'Catemu',6);
INSERT INTO COMUNA VALUES (68,'Llaillay',6);
INSERT INTO COMUNA VALUES (69,'Panquehue',6);
INSERT INTO COMUNA VALUES (70,'Putaendo',6);
INSERT INTO COMUNA VALUES (71,'San Felipe',6);
INSERT INTO COMUNA VALUES (72,'Santa María',6);
INSERT INTO COMUNA VALUES (73,'Casablanca',6);
INSERT INTO COMUNA VALUES (74,'Concón',6);
INSERT INTO COMUNA VALUES (75,'Juan Fernández',6);
INSERT INTO COMUNA VALUES (76,'Puchuncaví',6);
INSERT INTO COMUNA VALUES (77,'Quilpué',6);
INSERT INTO COMUNA VALUES (78,'Quintero',6);
INSERT INTO COMUNA VALUES (79,'Valparaíso',6);
INSERT INTO COMUNA VALUES (80,'Villa Alemana',6);
INSERT INTO COMUNA VALUES (81,'Viña del Mar',6);
INSERT INTO COMUNA VALUES (82,'Colina',7);
INSERT INTO COMUNA VALUES (83,'Lampa',7);
INSERT INTO COMUNA VALUES (84,'Tiltil',7);
INSERT INTO COMUNA VALUES (85,'Pirque',7);
INSERT INTO COMUNA VALUES (86,'Puente Alto',7);
INSERT INTO COMUNA VALUES (87,'San José de Maipo',7);
INSERT INTO COMUNA VALUES (88,'Buin',7);
INSERT INTO COMUNA VALUES (89,'Calera de Tango',7);
INSERT INTO COMUNA VALUES (90,'Paine',7);
INSERT INTO COMUNA VALUES (91,'San Bernardo',7);
INSERT INTO COMUNA VALUES (92,'Alhué',7);
INSERT INTO COMUNA VALUES (93,'Curacaví',7);
INSERT INTO COMUNA VALUES (94,'María Pinto',7);
INSERT INTO COMUNA VALUES (95,'Melipilla',7);
INSERT INTO COMUNA VALUES (96,'San Pedro',7);
INSERT INTO COMUNA VALUES (97,'Cerrillos',7);
INSERT INTO COMUNA VALUES (98,'Cerro Navia',7);
INSERT INTO COMUNA VALUES (99,'Conchalí',7);
INSERT INTO COMUNA VALUES (100,'El Bosque',7);
INSERT INTO COMUNA VALUES (101,'Estación Central',7);
INSERT INTO COMUNA VALUES (102,'Huechuraba',7);
INSERT INTO COMUNA VALUES (103,'Independencia',7);
INSERT INTO COMUNA VALUES (104,'La Cisterna',7);
INSERT INTO COMUNA VALUES (105,'La Granja',7);
INSERT INTO COMUNA VALUES (106,'La Florida',7);
INSERT INTO COMUNA VALUES (107,'La Pintana',7);
INSERT INTO COMUNA VALUES (108,'La Reina',7);
INSERT INTO COMUNA VALUES (109,'Las Condes',7);
INSERT INTO COMUNA VALUES (110,'Lo Barnechea',7);
INSERT INTO COMUNA VALUES (111,'Lo Espejo',7);
INSERT INTO COMUNA VALUES (112,'Lo Prado',7);
INSERT INTO COMUNA VALUES (113,'Macul',7);
INSERT INTO COMUNA VALUES (114,'Maipú',7);
INSERT INTO COMUNA VALUES (115,'Ñuñoa',7);
INSERT INTO COMUNA VALUES (116,'Pedro Aguirre Cerda',7);
INSERT INTO COMUNA VALUES (117,'Peñalolén',7);
INSERT INTO COMUNA VALUES (118,'Providencia',7);
INSERT INTO COMUNA VALUES (119,'Pudahuel',7);
INSERT INTO COMUNA VALUES (120,'Quilicura',7);
INSERT INTO COMUNA VALUES (121,'Quinta Normal',7);
INSERT INTO COMUNA VALUES (122,'Recoleta',7);
INSERT INTO COMUNA VALUES (123,'Renca',7);
INSERT INTO COMUNA VALUES (124,'San Miguel',7);
INSERT INTO COMUNA VALUES (125,'San Joaquín',7);
INSERT INTO COMUNA VALUES (126,'San Ramón',7);
INSERT INTO COMUNA VALUES (127,'Santiago',7);
INSERT INTO COMUNA VALUES (128,'Vitacura',7);
INSERT INTO COMUNA VALUES (129,'El Monte',7);
INSERT INTO COMUNA VALUES (130,'Isla de Maipo',7);
INSERT INTO COMUNA VALUES (131,'Padre Hurtado',7);
INSERT INTO COMUNA VALUES (132,'Peñaflor',7);
INSERT INTO COMUNA VALUES (133,'Talagante',7);
INSERT INTO COMUNA VALUES (134,'Codegua',8);
INSERT INTO COMUNA VALUES (135,'Coínco',8);
INSERT INTO COMUNA VALUES (136,'Coltauco',8);
INSERT INTO COMUNA VALUES (137,'Doñihue',8);
INSERT INTO COMUNA VALUES (138,'Graneros',8);
INSERT INTO COMUNA VALUES (139,'Las Cabras',8);
INSERT INTO COMUNA VALUES (140,'Machalí',8);
INSERT INTO COMUNA VALUES (141,'Malloa',8);
INSERT INTO COMUNA VALUES (142,'Mostazal',8);
INSERT INTO COMUNA VALUES (143,'Olivar',8);
INSERT INTO COMUNA VALUES (144,'Peumo',8);
INSERT INTO COMUNA VALUES (145,'Pichidegua',8);
INSERT INTO COMUNA VALUES (146,'Quinta de Tilcoco',8);
INSERT INTO COMUNA VALUES (147,'Rancagua',8);
INSERT INTO COMUNA VALUES (148,'Rengo',8);
INSERT INTO COMUNA VALUES (149,'Requínoa',8);
INSERT INTO COMUNA VALUES (150,'San Vicente de Tagua Tagua',8);
INSERT INTO COMUNA VALUES (151,'La Estrella',8);
INSERT INTO COMUNA VALUES (152,'Litueche',8);
INSERT INTO COMUNA VALUES (153,'Marchihue',8);
INSERT INTO COMUNA VALUES (154,'Navidad',8);
INSERT INTO COMUNA VALUES (155,'Peredones',8);
INSERT INTO COMUNA VALUES (156,'Pichilemu',8);
INSERT INTO COMUNA VALUES (157,'Chépica',8);
INSERT INTO COMUNA VALUES (158,'Chimbarongo',8);
INSERT INTO COMUNA VALUES (159,'Lolol',8);
INSERT INTO COMUNA VALUES (160,'Nancagua',8);
INSERT INTO COMUNA VALUES (161,'Palmilla',8);
INSERT INTO COMUNA VALUES (162,'Peralillo',8);
INSERT INTO COMUNA VALUES (163,'Placilla',8);
INSERT INTO COMUNA VALUES (164,'Pumanque',8);
INSERT INTO COMUNA VALUES (165,'San Fernando',8);
INSERT INTO COMUNA VALUES (166,'Santa Cruz',8);
INSERT INTO COMUNA VALUES (167,'Cauquenes',9);
INSERT INTO COMUNA VALUES (168,'Chanco',9);
INSERT INTO COMUNA VALUES (169,'Pelluhue',9);
INSERT INTO COMUNA VALUES (170,'Curicó',9);
INSERT INTO COMUNA VALUES (171,'Hualañé',9);
INSERT INTO COMUNA VALUES (172,'Licantén',9);
INSERT INTO COMUNA VALUES (173,'Molina',9);
INSERT INTO COMUNA VALUES (174,'Rauco',9);
INSERT INTO COMUNA VALUES (175,'Romeral',9);
INSERT INTO COMUNA VALUES (176,'Sagrada Familia',9);
INSERT INTO COMUNA VALUES (177,'Teno',9);
INSERT INTO COMUNA VALUES (178,'Vichuquén',9);
INSERT INTO COMUNA VALUES (179,'Colbún',9);
INSERT INTO COMUNA VALUES (180,'Linares',9);
INSERT INTO COMUNA VALUES (181,'Longaví',9);
INSERT INTO COMUNA VALUES (182,'Parral',9);
INSERT INTO COMUNA VALUES (183,'Retiro',9);
INSERT INTO COMUNA VALUES (184,'San Javier',9);
INSERT INTO COMUNA VALUES (185,'Villa Alegre',9);
INSERT INTO COMUNA VALUES (186,'Yerbas Buenas',9);
INSERT INTO COMUNA VALUES (187,'Constitución',9);
INSERT INTO COMUNA VALUES (188,'Curepto',9);
INSERT INTO COMUNA VALUES (189,'Empedrado',9);
INSERT INTO COMUNA VALUES (190,'Maule',9);
INSERT INTO COMUNA VALUES (191,'Pelarco',9);
INSERT INTO COMUNA VALUES (192,'Pencahue',9);
INSERT INTO COMUNA VALUES (193,'Río Claro',9);
INSERT INTO COMUNA VALUES (194,'San Clemente',9);
INSERT INTO COMUNA VALUES (195,'San Rafael',9);
INSERT INTO COMUNA VALUES (196,'Talca',9);
INSERT INTO COMUNA VALUES (197,'Bulnes',10);
INSERT INTO COMUNA VALUES (198,'Chillán',10);
INSERT INTO COMUNA VALUES (199,'Chillán Viejo',10);
INSERT INTO COMUNA VALUES (200,'Cobquecura',10);
INSERT INTO COMUNA VALUES (201,'Coelemu',10);
INSERT INTO COMUNA VALUES (202,'Coihueco',10);
INSERT INTO COMUNA VALUES (203,'El Carmen',10);
INSERT INTO COMUNA VALUES (204,'Ninhue',10);
INSERT INTO COMUNA VALUES (205,'Ñiquen',10);
INSERT INTO COMUNA VALUES (206,'Pemuco',10);
INSERT INTO COMUNA VALUES (207,'Pinto',10);
INSERT INTO COMUNA VALUES (208,'Portezuelo',10);
INSERT INTO COMUNA VALUES (209,'Quirihue',10);
INSERT INTO COMUNA VALUES (210,'Ránquil',10);
INSERT INTO COMUNA VALUES (211,'Treguaco',10);
INSERT INTO COMUNA VALUES (212,'Quillón',10);
INSERT INTO COMUNA VALUES (213,'San Carlos',10);
INSERT INTO COMUNA VALUES (214,'San Fabián',10);
INSERT INTO COMUNA VALUES (215,'San Ignacio',10);
INSERT INTO COMUNA VALUES (216,'San Nicolás',10);
INSERT INTO COMUNA VALUES (217,'Yungay',10);
INSERT INTO COMUNA VALUES (218,'Arauco',11);
INSERT INTO COMUNA VALUES (219,'Cañete',11);
INSERT INTO COMUNA VALUES (220,'Contulmo',11);
INSERT INTO COMUNA VALUES (221,'Curanilahue',11);
INSERT INTO COMUNA VALUES (222,'Lebu',11);
INSERT INTO COMUNA VALUES (223,'Los Álamos',11);
INSERT INTO COMUNA VALUES (224,'Tirúa',11);
INSERT INTO COMUNA VALUES (225,'Alto Biobío',11);
INSERT INTO COMUNA VALUES (226,'Antuco',11);
INSERT INTO COMUNA VALUES (227,'Cabrero',11);
INSERT INTO COMUNA VALUES (228,'Laja',11);
INSERT INTO COMUNA VALUES (229,'Los Ángeles',11);
INSERT INTO COMUNA VALUES (230,'Mulchén',11);
INSERT INTO COMUNA VALUES (231,'Nacimiento',11);
INSERT INTO COMUNA VALUES (232,'Negrete',11);
INSERT INTO COMUNA VALUES (233,'Quilaco',11);
INSERT INTO COMUNA VALUES (234,'Quilleco',11);
INSERT INTO COMUNA VALUES (235,'San Rosendo',11);
INSERT INTO COMUNA VALUES (236,'Santa Bárbara',11);
INSERT INTO COMUNA VALUES (237,'Tucapel',11);
INSERT INTO COMUNA VALUES (238,'Yumbel',11);
INSERT INTO COMUNA VALUES (239,'Chiguayante',11);
INSERT INTO COMUNA VALUES (240,'Concepción',11);
INSERT INTO COMUNA VALUES (241,'Coronel',11);
INSERT INTO COMUNA VALUES (242,'Florida',11);
INSERT INTO COMUNA VALUES (243,'Hualpén',11);
INSERT INTO COMUNA VALUES (244,'Hualqui',11);
INSERT INTO COMUNA VALUES (245,'Lota',11);
INSERT INTO COMUNA VALUES (246,'Penco',11);
INSERT INTO COMUNA VALUES (247,'San Pedro de La Paz',11);
INSERT INTO COMUNA VALUES (248,'Santa Juana',11);
INSERT INTO COMUNA VALUES (249,'Talcahuano',11);
INSERT INTO COMUNA VALUES (250,'Tomé',11);
INSERT INTO COMUNA VALUES (251,'Carahue',12);
INSERT INTO COMUNA VALUES (252,'Cholchol',12);
INSERT INTO COMUNA VALUES (253,'Cunco',12);
INSERT INTO COMUNA VALUES (254,'Curarrehue',12);
INSERT INTO COMUNA VALUES (255,'Freire',12);
INSERT INTO COMUNA VALUES (256,'Galvarino',12);
INSERT INTO COMUNA VALUES (257,'Gorbea',12);
INSERT INTO COMUNA VALUES (258,'Lautaro',12);
INSERT INTO COMUNA VALUES (259,'Loncoche',12);
INSERT INTO COMUNA VALUES (260,'Melipeuco',12);
INSERT INTO COMUNA VALUES (261,'Nueva Imperial',12);
INSERT INTO COMUNA VALUES (262,'Padre Las Casas',12);
INSERT INTO COMUNA VALUES (263,'Perquenco',12);
INSERT INTO COMUNA VALUES (264,'Pitrufquén',12);
INSERT INTO COMUNA VALUES (265,'Pucón',12);
INSERT INTO COMUNA VALUES (266,'Saavedra',12);
INSERT INTO COMUNA VALUES (267,'Temuco',12);
INSERT INTO COMUNA VALUES (268,'Teodoro Schmidt',12);
INSERT INTO COMUNA VALUES (269,'Toltén',12);
INSERT INTO COMUNA VALUES (270,'Vilcún',12);
INSERT INTO COMUNA VALUES (271,'Villarrica',12);
INSERT INTO COMUNA VALUES (272,'Angol',12);
INSERT INTO COMUNA VALUES (273,'Collipulli',12);
INSERT INTO COMUNA VALUES (274,'Curacautín',12);
INSERT INTO COMUNA VALUES (275,'Ercilla',12);
INSERT INTO COMUNA VALUES (276,'Lonquimay',12);
INSERT INTO COMUNA VALUES (277,'Los Sauces',12);
INSERT INTO COMUNA VALUES (278,'Lumaco',12);
INSERT INTO COMUNA VALUES (279,'Purén',12);
INSERT INTO COMUNA VALUES (280,'Renaico',12);
INSERT INTO COMUNA VALUES (281,'Traiguén',12);
INSERT INTO COMUNA VALUES (282,'Victoria',12);
INSERT INTO COMUNA VALUES (283,'Corral',13);
INSERT INTO COMUNA VALUES (284,'Lanco',13);
INSERT INTO COMUNA VALUES (285,'Los Lagos',13);
INSERT INTO COMUNA VALUES (286,'Máfil',13);
INSERT INTO COMUNA VALUES (287,'Mariquina',13);
INSERT INTO COMUNA VALUES (288,'Paillaco',13);
INSERT INTO COMUNA VALUES (289,'Panguipulli',13);
INSERT INTO COMUNA VALUES (290,'Valdivia',13);
INSERT INTO COMUNA VALUES (291,'Futrono',13);
INSERT INTO COMUNA VALUES (292,'La Unión',13);
INSERT INTO COMUNA VALUES (293,'Lago Ranco',13);
INSERT INTO COMUNA VALUES (294,'Río Bueno',13);
INSERT INTO COMUNA VALUES (295,'Ancud',14);
INSERT INTO COMUNA VALUES (296,'Castro',14);
INSERT INTO COMUNA VALUES (297,'Chonchi',14);
INSERT INTO COMUNA VALUES (298,'Curaco de Vélez',14);
INSERT INTO COMUNA VALUES (299,'Dalcahue',14);
INSERT INTO COMUNA VALUES (300,'Puqueldón',14);
INSERT INTO COMUNA VALUES (301,'Queilén',14);
INSERT INTO COMUNA VALUES (302,'Quemchi',14);
INSERT INTO COMUNA VALUES (303,'Quellón',14);
INSERT INTO COMUNA VALUES (304,'Quinchao',14);
INSERT INTO COMUNA VALUES (305,'Calbuco',14);
INSERT INTO COMUNA VALUES (306,'Cochamó',14);
INSERT INTO COMUNA VALUES (307,'Fresia',14);
INSERT INTO COMUNA VALUES (308,'Frutillar',14);
INSERT INTO COMUNA VALUES (309,'Llanquihue',14);
INSERT INTO COMUNA VALUES (310,'Los Muermos',14);
INSERT INTO COMUNA VALUES (311,'Maullín',14);
INSERT INTO COMUNA VALUES (312,'Puerto Montt',14);
INSERT INTO COMUNA VALUES (313,'Puerto Varas',14);
INSERT INTO COMUNA VALUES (314,'Osorno',14);
INSERT INTO COMUNA VALUES (315,'Puero Octay',14);
INSERT INTO COMUNA VALUES (316,'Purranque',14);
INSERT INTO COMUNA VALUES (317,'Puyehue',14);
INSERT INTO COMUNA VALUES (318,'Río Negro',14);
INSERT INTO COMUNA VALUES (319,'San Juan de la Costa',14);
INSERT INTO COMUNA VALUES (320,'San Pablo',14);
INSERT INTO COMUNA VALUES (321,'Chaitén',14);
INSERT INTO COMUNA VALUES (322,'Futaleufú',14);
INSERT INTO COMUNA VALUES (323,'Hualaihué',14);
INSERT INTO COMUNA VALUES (324,'Palena',14);
INSERT INTO COMUNA VALUES (325,'Aisén',15);
INSERT INTO COMUNA VALUES (326,'Cisnes',15);
INSERT INTO COMUNA VALUES (327,'Guaitecas',15);
INSERT INTO COMUNA VALUES (328,'Cochrane',15);
INSERT INTO COMUNA VALUES (329,'O higgins',15);
INSERT INTO COMUNA VALUES (330,'Tortel',15);
INSERT INTO COMUNA VALUES (331,'Coihaique',15);
INSERT INTO COMUNA VALUES (332,'Lago Verde',15);
INSERT INTO COMUNA VALUES (333,'Chile Chico',15);
INSERT INTO COMUNA VALUES (334,'Río Ibáñez',15);
INSERT INTO COMUNA VALUES (335,'Antártica',16);
INSERT INTO COMUNA VALUES (336,'Cabo de Hornos',16);
INSERT INTO COMUNA VALUES (337,'Laguna Blanca',16);
INSERT INTO COMUNA VALUES (338,'Punta Arenas',16);
INSERT INTO COMUNA VALUES (339,'Río Verde',16);
INSERT INTO COMUNA VALUES (340,'San Gregorio',16);
INSERT INTO COMUNA VALUES (341,'Porvenir',16);
INSERT INTO COMUNA VALUES (342,'Primavera',16);
INSERT INTO COMUNA VALUES (343,'Timaukel',16);
INSERT INTO COMUNA VALUES (344,'Natales',16);
INSERT INTO COMUNA VALUES (345,'Torres del Paine',16);
INSERT INTO COMUNA VALUES (346,'Cabildo',6);